# Generated by Django 4.0.3 on 2022-12-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_remove_appointment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
